# Generated by Django 3.2 on 2022-04-17 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='turn',
        ),
        migrations.AddField(
            model_name='board',
            name='turn',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
