# Generated by Django 3.2 on 2022-04-17 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20220417_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='created_on',
            new_name='created_at',
        ),
    ]
