# Generated by Django 3.2 on 2022-04-18 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_auto_20220418_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
