# Generated by Django 3.2 on 2022-05-08 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='value',
            field=models.CharField(blank=True, choices=[('J', 'JUMP'), ('D', 'DIAGONAL'), ('P', 'PUSH'), ('S', 'SWITCH')], default=None, max_length=255, null=True),
        ),
    ]
